server:
  port: 8080

spring:
  datasource:
    username: root
    password: a1b2c3d4-
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/static/assets/db/changelog/db.changelog-master.xml

indexing-settings:
  sites:
    - url: http://info.cern.ch
      name: http://info.cern.ch - home of the first website
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru

jsoupFakePerformance:
  userAgent: GamaSearchEngine
  referrer: http://www.google.com