server:
  port: 8081

spring:
  datasource:
    username: root
    password: a1b2c3d4-
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/static/assets/db/changelog/db.changelog-master.xml

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: https://1cistline.ru/
#      name: Истлайн
#    - url: http://www.cimus.biz
#      name: Цимус
    - url: https://strike-ball.ru
      name: Магазин "Легион"

jsoupFakePerformance:
  userAgent: GamaSearchEngine
  referrer: http://www.searcher.mu