server:
  port: 8080

spring:
  datasource:
    username: root
    password: a1b2c3d4-
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/static/assets/db/changelog/db.changelog-master.xml

indexing-settings:
  sites:
    - url: https://skillbox.ru/
      name: Skillbox

incorrect-page-endings:
  endings:
    - doc
    - jpg
    - png
    - jpeg
    - bmp
    - txt
    - pdf
    - xls
    - docx
    - gif
    - webp



jsoupFakePerformance:
  userAgent: EasySimpleSearchEngine
  referrer: http://www.searcher.mu